export const loading: string;
export const container: string;
export const input: string;
export const suggestionsContainer: string;
export const suggestionsContainerOpen: string;
export const suggestion: string;
export const suggestionHighlighted: string;
export const suggestionAvatar: string;
export const suggestionText: string;
