export const ARC_LOAD_CACHED_STATE_PENDING = "ARC_LOAD_CACHED_STATE_PENDING";
export const ARC_LOAD_CACHED_STATE_FULFILLED = "ARC_LOAD_CACHED_STATE_FULFILLED";
export const ARC_LOAD_CACHED_STATE_REJECTED = "ARC_LOAD_CACHED_STATE_REJECTED";

export const ARC_GET_DAOS_PENDING = "ARC_GET_DAOS_PENDING";
export const ARC_GET_DAOS_FULFILLED = "ARC_GET_DAOS_FULFILLED";
export const ARC_GET_DAOS_REJECTED = "ARC_GET_DAOS_REJECTED";

export const ARC_GET_DAO_PENDING = "ARC_GET_DAO_PENDING";
export const ARC_GET_DAO_FULFILLED = "ARC_GET_DAO_FULFILLED";
export const ARC_GET_DAO_REJECTED = "ARC_GET_DAO_REJECTED";

export const ARC_CREATE_DAO = "ARC_CREATE_DAO";

export const ARC_CREATE_PROPOSAL = "ARC_CREATE_PROPOSAL";

export const ARC_GET_PROPOSAL_PENDING = "ARC_GET_PROPOSAL_PENDING";
export const ARC_GET_PROPOSAL_FULFILLED = "ARC_GET_PROPOSAL_FULFILLED";
export const ARC_GET_PROPOSAL_REJECTED = "ARC_GET_PROPOSAL_REJECTED";

export const ARC_VOTE = "ARC_VOTE";

export const ARC_STAKE = "ARC_STAKE";

export const ARC_REDEEM = "ARC_REDEEM";