export const ARC_INITIALIZATION = 'ARC_INITIALIZATION';
export const ARC_INITIALIZATION_PENDING = 'ARC_INITIALIZATION_PENDING';
export const ARC_INITIALIZATION_FULFILLED = 'ARC_INITIALIZATION_FULFILLED';
export const ARC_INITIALIZATION_REJECTED = 'ARC_INITIALIZATION_REJECTED';

export const ARC_GET_DAOS_PENDING = 'ARC_GET_DAOS_PENDING';
export const ARC_GET_DAOS_FULFILLED = 'ARC_GET_DAOS_FULFILLED';
export const ARC_GET_DAOS_REJECTED = 'ARC_GET_DAOS_REJECTED';

export const ARC_GET_DAO_PENDING = 'ARC_GET_DAO_PENDING';
export const ARC_GET_DAO_FULFILLED = 'ARC_GET_DAO_FULFILLED';
export const ARC_GET_DAO_REJECTED = 'ARC_GET_DAO_REJECTED';

export const ARC_CREATE_DAO_PENDING = 'ARC_CREATE_DAO_PENDING';
export const ARC_CREATE_DAO_FULFILLED = 'ARC_CREATE_DAO_FULFILLED';
export const ARC_CREATE_DAO_REJECTED = 'ARC_CREATE_DAO_REJECTED';

export const ARC_CREATE_PROPOSITION_PENDING = 'ARC_CREATE_PROPOSITION_PENDING';
export const ARC_CREATE_PROPOSITION_FULFILLED = 'ARC_CREATE_PROPOSITION_FULFILLED';
export const ARC_CREATE_PROPOSITION_REJECTED = 'ARC_CREATE_PROPOSITION_REJECTED';

export const ARC_VOTE_PENDING = 'ARC_VOTE_PENDING';
export const ARC_VOTE_FULFILLED = 'ARC_VOTE_FULFILLED';
export const ARC_VOTE_REJECTED = 'ARC_VOTE_REJECTED';

export const API_URL = process.env.API_URL || 'http://127.0.0.1:3001';