export const ARC_INITIALIZATION = 'ARC_INITIALIZATION';
export const ARC_INITIALIZATION_PENDING = 'ARC_INITIALIZATION_PENDING';
export const ARC_INITIALIZATION_FULFILLED = 'ARC_INITIALIZATION_FULFILLED';
export const ARC_INITIALIZATION_REJECTED = 'ARC_INITIALIZATION_REJECTED';

export const ARC_GET_DAOS = 'ARC_GET_DAOS';
export const ARC_GET_DAOS_PENDING = 'ARC_GET_DAOS_PENDING';
export const ARC_GET_DAOS_FULFILLED = 'ARC_GET_DAOS_FULFILLED';
export const ARC_GET_DAOS_REJECTED = 'ARC_GET_DAOS_REJECTED';