export enum ActionTypes {
  WEB3_CONNECT = "WEB3_CONNECT",
  WEB3_SET_ACCOUNT = "WEB3_SET_ACCOUNT",
  WEB3_ON_ETH_BALANCE_CHANGE = "WEB3_ON_ETH_BALANCE_CHANGE",
  WEB3_ON_GEN_BALANCE_CHANGE = "WEB3_ON_GEN_BALANCE_CHANGE",
  WEB3_ON_GEN_STAKING_ALLOWANCE_CHANGE = "WEB3_ON_GEN_STAKING_ALLOWANCE_CHANGE",
  APPROVE_STAKING_GENS = "APPROVE_STAKING_GENS",
  OTHER_ACTION = "__any_other_action_type__",
}
