export const container: string;
export const yesWinning: string;
export const noWinning: string;
export const yesVotesCircle: string;
export const noVotesCircle: string;
export const circleChartCircle: string;
export const circleChartFill: string;
export const circleChartCircleNegative: string;
export const circleChartAppear: string;
