export const clearfix: string;
export const wrapper: string;
export const loading: string;
export const dao: string;
export const daoAvatar: string;
export const daoLink: string;
export const daoName: string;
export const daoInfo: string;
export const daoListHeader: string;
