export const proposalSummary: string;
export const schemeRegistrar: string;
export const detailView: string;
export const transactionModal: string;
export const summaryTitle: string;
export const summaryDetails: string;
export const transferAmount: string;
export const accountName: string;
export const transferType: string;
